### ISSUE TITLE
Does this work with FMS 19?

### ISSUE THREAD

**Issue by dani-phillips** [thomann061/fmrest#11]
Sorry, I didn't know where else to put this. 

My question is, does this work with FMS 19's data API as well? Looking to build a web app that needs to pull some information from a FileMaker database on FileMaker Server 19.2.1.23 and I need to know if there's any issues or differences. 

Thank you,
Dani.

**Comment by yehoshuasandler** [comment]
I'm not sure this repo has the capacity to stay up to date with newer versions of FM unfortunately. If you would like to send me an email I have some working code that I wrote and reuse at work in every instance I interact with FM. We use FM almost exclusively as our Databases.  My personal address is 

joshua@jshoemaker.dev

**Comment by dani-phillips** [comment]
Thank you Joshua, I'll go ahead and send an email as soon as I can.
