### ISSUE TITLE
Error: Cannot find module 'gulp'

### ISSUE THREAD

**Issue by dani-phillips** [thomann061/fmrest#12]
I get this error when trying to use this package. I've attached a screenshot of the full error message (the white boxes are to hide my username/other private stuff).

![fmrest-error](https://user-images.githubusercontent.com/54700061/111895580-dc783380-89d0-11eb-89ed-bf758e74d3a9.png)

**Comment by novice2194** [comment]
hello， how do you solve this problem，Can you tell me how to solve it

**Comment by dani-phillips** [comment]
@novice2194 Sorry, I don't know how to resolve it. I just posted the issue hoping the author could help.

**Comment by thomann061** [comment]
please try 2.3.1 on npm

**Comment by dani-phillips** [comment]
> please try 2.3.1 on npm

I'm using it now and it seems to be working. Hope you'll take a look at my other issue regarding token refreshing error.
